before_install:
 - sudo apt-get update -qq
install:
 - sudo apt-get install -qq libboost-regex1.48-dev libboost-thread1.48-dev libboost-system1.48-dev libboost1.48-dev
language: cpp
compiler: clang
script: 
 - ./build.sh
 - ./test.sh
 